"""empty message

Revision ID: 3183db0b7af5
Revises: 
Create Date: 2016-12-22 11:17:06.188871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3183db0b7af5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=True),
    sa.Column('contract_type', sa.String(length=100), nullable=True),
    sa.Column('contract_num', sa.String(length=100), nullable=False),
    sa.Column('contract_scale', sa.Float(), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=False),
    sa.Column('package_name', sa.String(length=100), nullable=False),
    sa.Column('app_name', sa.String(length=100), nullable=False),
    sa.Column('app_type', sa.String(length=100), nullable=False),
    sa.Column('preview_link', sa.String(length=100), nullable=False),
    sa.Column('track_link', sa.String(length=100), nullable=False),
    sa.Column('material', sa.String(length=100), nullable=True),
    sa.Column('startTime', sa.String(length=100), nullable=False),
    sa.Column('endTime', sa.String(length=100), nullable=False),
    sa.Column('platform', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('daily_type', sa.String(length=100), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('total_type', sa.String(length=100), nullable=True),
    sa.Column('distribution', sa.String(length=100), nullable=False),
    sa.Column('authorized', sa.String(length=100), nullable=False),
    sa.Column('named_rule', sa.String(length=100), nullable=False),
    sa.Column('KPI', sa.String(length=100), nullable=False),
    sa.Column('settlement', sa.String(length=100), nullable=False),
    sa.Column('period', sa.String(length=100), nullable=False),
    sa.Column('remark', sa.String(length=100), nullable=False),
    sa.Column('email_time', sa.Float(), nullable=False),
    sa.Column('email_users', sa.String(length=100), nullable=False),
    sa.Column('email_tempalte', sa.Integer(), nullable=False),
    sa.Column('createdTime', sa.String(length=100), nullable=False),
    sa.Column('updateTime', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('createdTime', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('country_price', sa.Float(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('daily_budget', sa.Float(), nullable=True),
    sa.Column('daily_type', sa.String(length=100), nullable=True),
    sa.Column('total_budget', sa.Float(), nullable=True),
    sa.Column('total_type', sa.String(length=100), nullable=True),
    sa.Column('KPI', sa.String(length=100), nullable=False),
    sa.Column('contract_type', sa.String(length=100), nullable=False),
    sa.Column('contract_scale', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'customers', sa.Column('last_datetime', sa.DateTime(), nullable=True))
    op.add_column(u'customers', sa.Column('status', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'customers', ['company_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='unique')
    op.drop_column(u'customers', 'status')
    op.drop_column(u'customers', 'last_datetime')
    op.drop_table('permissions')
    op.drop_table('history')
    op.drop_table('offer')
    op.drop_table('group')
    # ### end Alembic commands ###
