"""empty message

Revision ID: e56ee4bdbce1
Revises: 3183db0b7af5
Create Date: 2016-12-22 11:18:14.821233

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e56ee4bdbce1'
down_revision = '3183db0b7af5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'offer_ibfk_1', 'offer', type_='foreignkey')
    op.drop_column('offer', 'customer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('customer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'offer_ibfk_1', 'offer', 'customers', ['customer_id'], ['id'])
    # ### end Alembic commands ###
